title: "Minhas Web Novels"
description: "Um site para publicar minhas histórias."
url: "https://Marlytos6.github.io"
baseurl: "/Web_Novel"
timezone: 'America/Sao_Paulo'
plugins:
  - jekyll-feed
  - jekyll-seo-tag