title: "Minhas Web Novels"
description: "Um site para publicar minhas histórias."
baseurl: "/Web_Novel"
url: "https://marlytos.github.io"
timezone: 'America/Sao_Paulo'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  